version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: tutorial/requirements.txt

mkdocs:
  configuration: tutorial/mkdocs.yml

system_packages:
  - doxygen