site_name: xTorch
theme:
  name: material  # looks clean and modern
nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorials:
      - Hello World: tutorials/hello_world.md
      - Settings: tutorials/settings.md
plugins:
  - mkdocstrings:
      handlers:
        cpp:
          options:
            include_paths: ["include/"]  # Path to C++ headers
            clang:
              args: ["-std=c++17", "-I./include"]  # Compiler flags