#pragma once


#include "add_noise.h"
#include "background_noise_addition.h"
#include "de_reverberation.h"
#include "frequency_masking.h"
#include "griffin_lim.h"
#include "inverse_mel_scale.h"
#include "mel_scale.h"
#include "mel_spectrogram.h"
#include "mfcc.h"
#include "pitch_shift.h"
#include "resample.h"
#include "sliding_window_cmn.h"
#include "spectrogram.h"
#include "speed_perturbation.h"
#include "time_masking.h"
#include "time_stretch.h"
#include "time_warping.h"
#include ""