name: Build xtorch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential wget unzip libcurl4-openssl-dev libopencv-dev zlib1g-dev libssl-dev liblzma-dev libarchive-dev libtar-dev libzip-dev libsndfile1-dev libhdf5-dev

      - name: Download LibTorch
        run: |
          wget https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-2.2.0%2Bcpu.zip
          unzip libtorch-shared-with-deps-2.2.0+cpu.zip
          mv libtorch /tmp/libtorch

      - name: Build xtorch
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_PREFIX_PATH=/tmp/libtorch  -DSndFile_DIR=/usr/lib/x86_64-linux-gnu/cmake ..
          make
